[package]
name = "rbcp-core"
version = "2.0.2-beta"
edition = "2021"

[dependencies]
filetime = "0.2.25"
rand = "0.8.5"
rayon = "1.8"
glob = "0.3"
ctrlc = "3.5.1"
serde = { version = "1.0", features = ["derive"] }
